default: &default
  adapter: postgresql
  encoding: unicode
  host: 107.170.81.100 #dirección del servidor de base de datos
  pool: 5
  username: omnibuild
  password: holamundo

development:
  <<: *default
  database: mitigacion_development

test:
  <<: *default
  database: mitigacion_test

production:
  <<: *default
  database: mitigacion_production
